@echo off
echo Running git add...
git add .
echo Running git commit...
git commit -m "Fix: Update API URL to Render and bypass Google Login with Guest mode"
echo Running git push...
git push origin master:main
echo Done.
