@echo off
echo Running git add...
git add .
echo Running git commit...
git commit -m "Fix: Add missing routes and utils, correct package versions for Render"
echo Running git push...
git push origin main
echo Done.
